from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api import *

ytt_api = YouTubeTranscriptApi()
transcript = ytt_api.fetch("m4hv7HQT_cQ")
# for items in fetched_transcript:
#     print(items.text)


print(
    transcript.video_id,
    transcript.language,
    transcript.language_code,
    # whether it has been manually created or generated by YouTube
    transcript.is_generated,
    # whether this transcript can be translated or not
    transcript.is_translatable,
    # a list of languages the transcript can be translated to
    transcript.translation_languages,
)

