from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api import *

ytt_api = YouTubeTranscriptApi()
transcript = ytt_api.fetch("e8B0AzmXPV8")
# for items in fetched_transcript:
#     print(items.text)


print(
    transcript.video_id,
    transcript.language,
    transcript.language_code,
    # whether it has been manually created or generated by YouTube
    transcript.is_generated,
    # whether this transcript can be translated or not
    # transcript.is_translatable,
    # # a list of languages the transcript can be translated to
    # transcript.translation_languages,
)


# for transcript in transcript_list:
# 
    # # the Transcript object provides metadata properties
    # print(
    #     transcript.video_id,
    #     transcript.language,
    #     transcript.language_code,
    #     # whether it has been manually created or generated by YouTube
    #     transcript.is_generated,
    #     # whether this transcript can be translated or not
    #     transcript.is_translatable,
    #     # a list of languages the transcript can be translated to
    #     transcript.translation_languages,
    # )

    # # fetch the actual transcript data
    # print(transcript.fetch())

    # # translating the transcript will return another transcript object
    # print(transcript.translate('en').fetch())